# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c53d549520251546b455332ea12aeaa559c0593bcab309074cf68fa82bd6eafda52239f3c377243f1c61714dbb0aa1cccd646f9f7cf9d7e05228dbe25593fe7c

test:
  secret_key_base: 7006a43a2df2ae7b978295b5056f5c42fa04323dfae3852de874e8adae64145c3d639adb8168abb0444dd48150faeae4f18b831f912cfb66a2cfdbe4cbec8448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
